### ISSUE TITLE
Captcha solver seems to be broken

### ISSUE THREAD

**Issue by Fooftilly** [FarisHijazi/Rarbg-Enhancer-UserScript#7] opened 2021-11-28 13:33 UTC
When the script is enables, captcha page just reloads endlessly.

**Comment by FarisHijazi** [comment] 2021-11-28 21:50
## Check run conditions

Could you provide me with a way to reproduce this. Please check which of the 2 scripts you're using:
- Rarbg-CAPTCHA-solver.user.js
- Rarbg-Enhancer-UserScript.user.js

And make sure you don't have 2 running at the same time

Also please provide the exact rarbg URL you're trying to access

## Provide me with console output

Also press F12 > Console > Console settings > and check "Preserve log"

and provide me with an image of what the console is outputting

thank you

**Comment by Fooftilly** [comment] 2022-01-07 21:57
First, sorry for a late response, i am using Rarbg-Enhancer-UserScript.user.js on Firefox.
Here's the console log:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://statsy.net/a.php?ref=threat_defence.rarbg.com&res=760x1594&_=1641592489700. (Reason: CORS request did not succeed). Status code: (null).

Navigated to https://rarbggo.org/threat_defence.php?defence=2&sk=al5vexfsnk&cid=53693458&i=2957208576&ref_cookie=rarbggo.org&r=96865277
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://statsy.net/a.php?ref=threat_defence.rarbg.com&res=760x1094&_=1641592562400. (Reason: CORS request did not succeed). Status code: (null).

Script: RARBG Enhancer meta: 
Object { rawmdb: "function () {\n// ==UserScript==\n// @name         RARBG Enhancer\n// @namespace    https://github.com/FarisHijazi\n// @version      1.5.3\n// @description  Auto-solve CAPTCHA, infinite scroll, add a magnet link shortcut and thumbnails of torrents,\n// @description  adds a image search link in case you want to see more pics of the torrent, and more!\n// @author       Faris Hijazi\n//               with some code from https://greasyfork.org/en/users/2160-darkred\n// @grant        unsafeWindow\n// @grant        GM_setValue\n// @grant        GM_getValue\n// @grant        GM_download\n// @grant        GM_xmlhttpRequest\n// @icon         https://www.google.com/s2/favicons?domain=rarbg.com\n// @run-at       document-idle\n// @updateUrl    https://github.com/FarisHijazi/Rarbg-Enhancer-UserScript/raw/master/Rarbg-Enhancer-UserScript.user.js\n// @require      https://code.jquery.com/jquery-3.4.0.min.js\n// @require      https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.4/jszip.min.js\n// @require      https://unpkg.com/infinite-scroll@3.0.5/dist/infinite-scroll.pkgd.min.js\n// @require      https://raw.githubusercontent.com/ccampbell/mousetrap/master/mousetrap.min.js\n// @include      https://*rarbg.*\n// @include      /https?:\\/\\/.{0,8}rarbg.*\\.\\/*/\n// @include      /https?:\\/\\/.{0,8}rargb.*\\.\\/*/\n// @include      /https?:\\/\\/.*u=MTcyLjIxLjAuMXw6Ly9yYXJiZy50by90b3JyZW50LzIyMDg3MjYwfE1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS83OS4wLjM5NDUuMTMwIFNhZmFyaS81MzcuMzZ8ODc4MDQz.*/\n// @include      https://www.rarbg.is\n// @include      https://proxyrarbg.org\n// @include      https://rarbg.com\n// @include      https://rarbg.to\n// @include      https://rarbg2018.org\n// @include      https://rarbg2019.org\n// @include      https://rarbg2020.org\n// @include      https://rarbg2021.org\n// @include      https://rarbgaccess.org\n// @include      https://rarbgaccessed.org\n// @include      https://rarbgcdn.org\n// @include      https://rarbgcore.org\n// @include      https://rarbgdata.org\n// @include      https://rarbgenter.org\n// @include      https://rarbgget.org\n// @include      https://rarbggo.org\n// @include      https://rarbgindex.org\n// @include      https://rarbgmirror.com\n// @include      https://rarbgmirror.org\n// @include      https://rarbgmirrored.org\n// @include      https://rarbgp2p.org\n// @include      https://rarbgproxied.org\n// @include      https://rarbgproxies.org\n// @include      https://rarbgproxy.com\n// @include      https://rarbgproxy.org\n// @include      https://rarbgprx.org\n// @include      https://rarbgto.org\n// @include      https://rarbgtor.org\n// @include      https://rarbgtorrents.org\n// @include      https://rarbgunblock.com\n// @include      https://rarbgunblock.org\n// @include      https://rarbgunblocked.org\n// @include      https://rarbgway.org\n// @include      https://rarbgweb.org\n// @include      https://unblockedrarbg.org\n// @include      https://www.rarbg.is\n// @require      https://raw.githubusercontent.com/antimatter15/ocrad.js/master/ocrad.js\n// @noframes\n// ==/UserScript==\n    }", name: "RARBG Enhancer", namespace: "https://github.com/FarisHijazi", version: "1.5.3", description: (2) […], author: "Faris Hijazi", grant: (5) […], icon: "https://www.google.com/s2/favicons?domain=rarbg.com", "run-at": "document-idle", updateUrl: "https://github.com/FarisHijazi/Rarbg-Enhancer-UserScript/raw/master/Rarbg-Enhancer-UserScript.user.js", … }
RARBG Enhancer.user.js:96429:9
search engine: google 
Object { name: "Google", imageSearchUrl: imageSearchUrl(q)
 }
RARBG Enhancer.user.js:97735:21
tbody element not found! RARBG Enhancer.user.js:96585:27
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. eval line 4 > eval:96680:16
Binding keys to categories: RARBG Enhancer.user.js:97183:17
"v": "Movies" RARBG Enhancer.user.js:97185:21
"s": "TV show" RARBG Enhancer.user.js:97185:21
"m": "Music" RARBG Enhancer.user.js:97185:21
"w": "Software" RARBG Enhancer.user.js:97185:21
"x": "XXX" RARBG Enhancer.user.js:97185:21
"g": "Games" RARBG Enhancer.user.js:97185:21
"n": "Non XXX" RARBG Enhancer.user.js:97185:21
Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
Rarbg threat defence page RARBG Enhancer.user.js:96693:25
solving captcha... eval line 4 > eval line 97975 > Function:4:17
solveCAPTHA fetching image ... eval line 4 > eval line 97975 > Function:47:17
DOMException: CanvasRenderingContext2D.drawImage: Passed-in image is "broken" eval line 4 > eval line 97975 > Function:72:21
Navigated to https://rarbggo.org/threat_defence.php?defence=1&sk=al5vexfsnk&cid=53693458&i=2957208576&ref_cookie=rarbggo.org&r=96865277
Cookie “sk” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite threat_defence.php:51
Script: RARBG Enhancer meta: 
Object { rawmdb: "function () {\n// ==UserScript==\n// @name         RARBG Enhancer\n// @namespace    https://github.com/FarisHijazi\n// @version      1.5.3\n// @description  Auto-solve CAPTCHA, infinite scroll, add a magnet link shortcut and thumbnails of torrents,\n// @description  adds a image search link in case you want to see more pics of the torrent, and more!\n// @author       Faris Hijazi\n//               with some code from https://greasyfork.org/en/users/2160-darkred\n// @grant        unsafeWindow\n// @grant        GM_setValue\n// @grant        GM_getValue\n// @grant        GM_download\n// @grant        GM_xmlhttpRequest\n// @icon         https://www.google.com/s2/favicons?domain=rarbg.com\n// @run-at       document-idle\n// @updateUrl    https://github.com/FarisHijazi/Rarbg-Enhancer-UserScript/raw/master/Rarbg-Enhancer-UserScript.user.js\n// @require      https://code.jquery.com/jquery-3.4.0.min.js\n// @require      https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.4/jszip.min.js\n// @require      https://unpkg.com/infinite-scroll@3.0.5/dist/infinite-scroll.pkgd.min.js\n// @require      https://raw.githubusercontent.com/ccampbell/mousetrap/master/mousetrap.min.js\n// @include      https://*rarbg.*\n// @include      /https?:\\/\\/.{0,8}rarbg.*\\.\\/*/\n// @include      /https?:\\/\\/.{0,8}rargb.*\\.\\/*/\n// @include      /https?:\\/\\/.*u=MTcyLjIxLjAuMXw6Ly9yYXJiZy50by90b3JyZW50LzIyMDg3MjYwfE1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS83OS4wLjM5NDUuMTMwIFNhZmFyaS81MzcuMzZ8ODc4MDQz.*/\n// @include      https://www.rarbg.is\n// @include      https://proxyrarbg.org\n// @include      https://rarbg.com\n// @include      https://rarbg.to\n// @include      https://rarbg2018.org\n// @include      https://rarbg2019.org\n// @include      https://rarbg2020.org\n// @include      https://rarbg2021.org\n// @include      https://rarbgaccess.org\n// @include      https://rarbgaccessed.org\n// @include      https://rarbgcdn.org\n// @include      https://rarbgcore.org\n// @include      https://rarbgdata.org\n// @include      https://rarbgenter.org\n// @include      https://rarbgget.org\n// @include      https://rarbggo.org\n// @include      https://rarbgindex.org\n// @include      https://rarbgmirror.com\n// @include      https://rarbgmirror.org\n// @include      https://rarbgmirrored.org\n// @include      https://rarbgp2p.org\n// @include      https://rarbgproxied.org\n// @include      https://rarbgproxies.org\n// @include      https://rarbgproxy.com\n// @include      https://rarbgproxy.org\n// @include      https://rarbgprx.org\n// @include      https://rarbgto.org\n// @include      https://rarbgtor.org\n// @include      https://rarbgtorrents.org\n// @include      https://rarbgunblock.com\n// @include      https://rarbgunblock.org\n// @include      https://rarbgunblocked.org\n// @include      https://rarbgway.org\n// @include      https://rarbgweb.org\n// @include      https://unblockedrarbg.org\n// @include      https://www.rarbg.is\n// @require      https://raw.githubusercontent.com/antimatter15/ocrad.js/master/ocrad.js\n// @noframes\n// ==/UserScript==\n    }", name: "RARBG Enhancer", namespace: "https://github.com/FarisHijazi", version: "1.5.3", description: (2) […], author: "Faris Hijazi", grant: (5) […], icon: "https://www.google.com/s2/favicons?domain=rarbg.com", "run-at": "document-idle", updateUrl: "https://github.com/FarisHijazi/Rarbg-Enhancer-UserScript/raw/master/Rarbg-Enhancer-UserScript.user.js", … }
RARBG Enhancer.user.js:96429:9
search engine: google 
Object { name: "Google", imageSearchUrl: imageSearchUrl(q)
 }
RARBG Enhancer.user.js:97735:21
tbody element not found! RARBG Enhancer.user.js:96585:27
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. eval line 4 > eval:96680:16
Binding keys to categories: RARBG Enhancer.user.js:97183:17
"v": "Movies" RARBG Enhancer.user.js:97185:21
"s": "TV show" RARBG Enhancer.user.js:97185:21
"m": "Music" RARBG Enhancer.user.js:97185:21
"w": "Software" RARBG Enhancer.user.js:97185:21
"x": "XXX" RARBG Enhancer.user.js:97185:21
"g": "Games" RARBG Enhancer.user.js:97185:21
"n": "Non XXX" RARBG Enhancer.user.js:97185:21
Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
Navigated to https://rarbggo.org/threat_defence.php?defence=1&sk=al5vexfsnk&cid=53693458&i=2957208576&ref_cookie=rarbggo.org&r=96865277
Cookie “sk” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite threat_defence.php:51
Script: RARBG Enhancer meta: 
Object { rawmdb: "function () {\n// ==UserScript==\n// @name         RARBG Enhancer\n// @namespace    https://github.com/FarisHijazi\n// @version      1.5.3\n// @description  Auto-solve CAPTCHA, infinite scroll, add a magnet link shortcut and thumbnails of torrents,\n// @description  adds a image search link in case you want to see more pics of the torrent, and more!\n// @author       Faris Hijazi\n//               with some code from https://greasyfork.org/en/users/2160-darkred\n// @grant        unsafeWindow\n// @grant        GM_setValue\n// @grant        GM_getValue\n// @grant        GM_download\n// @grant        GM_xmlhttpRequest\n// @icon         https://www.google.com/s2/favicons?domain=rarbg.com\n// @run-at       document-idle\n// @updateUrl    https://github.com/FarisHijazi/Rarbg-Enhancer-UserScript/raw/master/Rarbg-Enhancer-UserScript.user.js\n// @require      https://code.jquery.com/jquery-3.4.0.min.js\n// @require      https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.4/jszip.min.js\n// @require      https://unpkg.com/infinite-scroll@3.0.5/dist/infinite-scroll.pkgd.min.js\n// @require      https://raw.githubusercontent.com/ccampbell/mousetrap/master/mousetrap.min.js\n// @include      https://*rarbg.*\n// @include      /https?:\\/\\/.{0,8}rarbg.*\\.\\/*/\n// @include      /https?:\\/\\/.{0,8}rargb.*\\.\\/*/\n// @include      /https?:\\/\\/.*u=MTcyLjIxLjAuMXw6Ly9yYXJiZy50by90b3JyZW50LzIyMDg3MjYwfE1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS83OS4wLjM5NDUuMTMwIFNhZmFyaS81MzcuMzZ8ODc4MDQz.*/\n// @include      https://www.rarbg.is\n// @include      https://proxyrarbg.org\n// @include      https://rarbg.com\n// @include      https://rarbg.to\n// @include      https://rarbg2018.org\n// @include      https://rarbg2019.org\n// @include      https://rarbg2020.org\n// @include      https://rarbg2021.org\n// @include      https://rarbgaccess.org\n// @include      https://rarbgaccessed.org\n// @include      https://rarbgcdn.org\n// @include      https://rarbgcore.org\n// @include      https://rarbgdata.org\n// @include      https://rarbgenter.org\n// @include      https://rarbgget.org\n// @include      https://rarbggo.org\n// @include      https://rarbgindex.org\n// @include      https://rarbgmirror.com\n// @include      https://rarbgmirror.org\n// @include      https://rarbgmirrored.org\n// @include      https://rarbgp2p.org\n// @include      https://rarbgproxied.org\n// @include      https://rarbgproxies.org\n// @include      https://rarbgproxy.com\n// @include      https://rarbgproxy.org\n// @include      https://rarbgprx.org\n// @include      https://rarbgto.org\n// @include      https://rarbgtor.org\n// @include      https://rarbgtorrents.org\n// @include      https://rarbgunblock.com\n// @include      https://rarbgunblock.org\n// @include      https://rarbgunblocked.org\n// @include      https://rarbgway.org\n// @include      https://rarbgweb.org\n// @include      https://unblockedrarbg.org\n// @include      https://www.rarbg.is\n// @require      https://raw.githubusercontent.com/antimatter15/ocrad.js/master/ocrad.js\n// @noframes\n// ==/UserScript==\n    }", name: "RARBG Enhancer", namespace: "https://github.com/FarisHijazi", version: "1.5.3", description: (2) […], author: "Faris Hijazi", grant: (5) […], icon: "https://www.google.com/s2/favicons?domain=rarbg.com", "run-at": "document-idle", updateUrl: "https://github.com/FarisHijazi/Rarbg-Enhancer-UserScript/raw/master/Rarbg-Enhancer-UserScript.user.js", … }
RARBG Enhancer.user.js:96429:9
search engine: google 
Object { name: "Google", imageSearchUrl: imageSearchUrl(q)
 }
RARBG Enhancer.user.js:97735:21
tbody element not found! RARBG Enhancer.user.js:96585:27
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. eval line 4 > eval:96680:16
Binding keys to categories: RARBG Enhancer.user.js:97183:17
"v": "Movies" RARBG Enhancer.user.js:97185:21
"s": "TV show" RARBG Enhancer.user.js:97185:21
"m": "Music" RARBG Enhancer.user.js:97185:21
"w": "Software" RARBG Enhancer.user.js:97185:21
"x": "XXX" RARBG Enhancer.user.js:97185:21
"g": "Games" RARBG Enhancer.user.js:97185:21
"n": "Non XXX" RARBG Enhancer.user.js:97185:21
Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
Navigated to https://rarbggo.org/threat_defence.php?defence=2&sk=qtw7c5f928&cid=53693444&i=2957210702&ref_cookie=rarbggo.org&r=81060424
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://statsy.net/a.php?ref=threat_defence.rarbg.com&res=760x1094&_=1641592572800. (Reason: CORS request did not succeed). Status code: (null).
```
![pic-window-220107-2258-18](https://user-images.githubusercontent.com/46610174/148612542-fd0cb2bf-52d7-454a-b5db-2730309dcb8e.png)

Maybe it has to do something with Cross-Origin Request Blocked in firefox?

**Comment by FarisHijazi** [comment] 2022-01-25 20:55
I tried to replicate the error, went to the same exact domain on firefox, everything works as it should

and I'm not getting the "cross origin request blocked"

**Comment by nicman23** [comment] 2022-03-02 13:09
hey i had this issue with violentmonkey. installing tampermonkey worked for me. it is a permission issue around unsafe window what ever that is.

**Comment by FarisHijazi** [comment] 2022-03-13 12:16
it's an elevated window that allows you to do more stuff like `eval()`, which is unfortunately needed for solving the CAPTCHA

I'll be closing this issue assuming that it works with Tampermonkey

**Closed as completed by FarisHijazi** 2022-03-13 12:16 UTC

**Comment by Klaster1** [comment] 2022-10-07 08:11
Not sure why you'd need `eval` or unsafe window for this. After reading through the issue, I resorted to creating [my own captcha solver](https://gist.github.com/Klaster1/dd7991d59fc8e6a7ec2544b47a12e4e9), tested to work in Firefox/Greasemonkey and Chrome/Violentmonkey.

**Comment by FarisHijazi** [comment] 2022-10-10 20:58
simply put, tesseract is too slow, OCRAD is much faster since it doesn't need to download anything
